name: Release UID2 Examples Image for Standard
run-name: ${{ inputs.release_type == 'Snapshot' && 'Publish Pre-release' || format('Release {0}', inputs.release_type)}} UID2 Examples Image for Standard by @${{ github.actor }}  
on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: 'The type of release'
        options:
        - Major
        - Minor
        - Patch
        - Snapshot

jobs:
  incrementVersionNumber:
    uses: IABTechLab/uid2-shared-actions/.github/workflows/shared-increase-version-number.yaml@kcc-UID2-2674-implement-shared-publish-to-docker-versioned
    with:
      release_type: ${{ inputs.release_type }}
      working_dir: publisher/standard
    secrets: inherit

  publishForStandard:
    uses: IABTechLab/uid2-shared-actions/.github/workflows/shared-publish-to-docker-versioned.yaml@kcc-UID2-2674-implement-shared-publish-to-docker-versioned
    needs: incrementVersionNumber
    with: 
      new_version: ${{ needs.incrementVersionNumber.outputs.new_version }}
      image_tag: ${{ needs.incrementVersionNumber.outputs.image_tag }}
      release_type: ${{ inputs.release_type }}
      docker_file: publisher/standard/Dockerfile
      docker_context: publisher/standard
      docker_image_name: IABTechLab/uid2-examples
      docker_registry: ghcr.io
    secrets: inherit
